[package]
name = "speedtestr"
version = "0.1.0"
authors = ["Zach Peters <zpeters@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
reqwest = "0.9.11"
serde_derive = "1.0.89"
serde = "1.0.89" 
serde_json = "1.0.39"
simplelog = "0.5.3"
log = "0.4.6"
failure = "0.1.5" 
